import '../testing/isolated-checkout';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { workspaceData } from '../testing/workspace-data';
import { executionPlan, resolveExecutionData, runtimeSelection } from '../test-data/execution';
import { diagnosticText, diagnosticData } from '../diagnostics/artifacts';
import { classifyExecutionFailure } from '../autocode/verify';
import { generatedInput, requiredData } from '../test-data/values';
import { mapRecording } from '../autocode/from-recording';
import { resolveScope, pinActiveScope } from '../projects/scope';
import { writeFixtureFile } from '../testing/synthetic-data';

async function main(){
 assert.equal(process.cwd(),process.env.AURA_SYNTHETIC_FIXTURE_ROOT,'Test Data fixtures must run in the independently guarded temporary worker.');
 const {scope,other,recording}=workspaceData();
 const registry=JSON.parse(fs.readFileSync('ai/projects/registry.json','utf8'));registry.applications[0].environments.stg={baseUrl:'https://staging.example.invalid/'};writeFixtureFile('ai/projects/registry.json',JSON.stringify(registry));
 const store=await import('../test-data/store');
 const before=store.readTestData(scope);
 assert.equal(before.schemaVersion,1);
 assert.equal(before.applicationId,scope.applicationId);
 const created=store.updateTestData(scope,before.version,{kind:'credential',profile:{name:'Operator',role:'admin',tags:['smoke'],environments:{qa:{username:'synthetic-operator',password:'synthetic-test-password'}}}});
 const profile=created.credentialProfiles[0];
 assert.ok(profile.id);
 assert.equal(profile.environments.qa.passwordConfigured,true);
 assert.ok(!JSON.stringify(created).includes('synthetic-test-password'),'API must not return passwords');
 assert.equal(Object.hasOwn(profile.environments.qa,'password'),false,'API GET never exposes a password property');
 assert.equal(Object.hasOwn(profile.environments.qa,'secretPayload'),false,'API GET never exposes encrypted payloads');
 assert.ok(!fs.readFileSync(store.testDataFile(scope),'utf8').includes('synthetic-test-password'),'store must encrypt passwords');
 const file=store.testDataFile(scope),original=fs.readFileSync(file,'utf8');
 assert.throws(()=>store.updateTestData(scope,before.version,{kind:'credential',profile:{id:profile.id,name:'Stale'}}),/changed/,'stale revision cannot overwrite');
 assert.equal(fs.readFileSync(file,'utf8'),original);
 let state=store.updateTestData(scope,created.version,{kind:'credential',profile:{id:profile.id,name:'Administrator'}});
 assert.equal(state.credentialProfiles[0].id,profile.id,'rename retains stable ID');
 assert.equal(store.resolveProfileCredentials(scope,profile.id).password,'synthetic-test-password','omitted password keeps encrypted secret');
 assert.equal(store.resolveProfileCredentials(scope,profile.id).email,'synthetic-operator');
 assert.ok(!JSON.stringify(state).includes('synthetic-operator'),'catalog never sends the username');
 assert.equal(store.readTestData(other).credentialProfiles.length,0,'foreign profiles not listed');
 assert.throws(()=>store.resolveProfileCredentials(other,profile.id),/CREDENTIAL_CONFIGURATION_FAILURE/);
 assert.throws(()=>store.updateTestData(other,store.readTestData(other).version,{kind:'credential',profile:{id:profile.id,name:'Foreign'}}),/another application/);
 state=store.updateTestData(scope,state.version,{kind:'credential',profile:{id:profile.id,name:'Administrator',environments:{qa:{password:'synthetic-new-secret'}}}});
 assert.equal(store.resolveProfileCredentials(scope,profile.id).password,'synthetic-new-secret','password replacement works');
 state=store.updateTestData(scope,state.version,{kind:'duplicateCredential',id:profile.id,name:'Standard User'});
 const second=state.credentialProfiles[1];assert.notEqual(second.id,profile.id);assert.equal(store.resolveProfileCredentials(scope,second.id).password,'synthetic-new-secret','duplicate reencrypts for its own ID');
 state=store.updateTestData(scope,state.version,{kind:'credential',profile:{id:second.id,name:second.name,environments:{stg:{username:'synthetic-staging-user',password:'synthetic-staging-secret'}}}});
 const staging=resolveScope({applicationId:scope.applicationId,environmentId:'stg'});assert.deepEqual(store.resolveProfileCredentials(staging,second.id),{email:'synthetic-staging-user',password:'synthetic-staging-secret'},'environment resolves a coherent credential pair');assert.throws(()=>store.credentialPreflight(staging,profile.id),/CREDENTIAL_CONFIGURATION_FAILURE/);
 state=store.updateTestData(scope,state.version,{kind:'duplicateCredential',id:profile.id,name:'Support User'});const third=state.credentialProfiles[2];
 state=store.updateTestData(scope,state.version,{kind:'data',profile:{name:'Enterprise',description:'',tags:['us'],data:{country:'US',quantity:3,enabled:true,optional:null,nested:{language:'en'}}}});
 const data=state.dataProfiles[0];
 state=store.updateTestData(scope,state.version,{kind:'examples',testCaseId:'TC_PROFILE',tags:['smoke'],rows:[profile,second].map(p=>({id:'',credentialProfileId:p.id,dataProfileId:data.id,tags:[p===profile?'admin':'standard'],enabled:true,overrides:{quantity:4}}))});
 const saved=fs.readFileSync(file,'utf8'),rows=state.testCases.TC_PROFILE.executionRows;
 assert.equal(rows.length,2);assert.equal(store.readTestData(scope).testCases.TC_PROFILE.executionRows.length,2,'restart reconstruction from JSON');
 assert.throws(()=>store.updateTestData(scope,state.version,{kind:'deleteCredential',id:profile.id}),/references/,'referenced profile cannot be deleted');
 const request={mode:'examples' as const,expectedVersion:state.version};
 let planned=executionPlan(scope,['TC_PROFILE'],request);
 assert.equal(planned.length,2,'Example rows remain separate executions');
 assert.notEqual(planned[0].profile.executionRowId,planned[1].profile.executionRowId);
 assert.equal(resolveExecutionData(scope,planned[0].selection).testData.quantity,4,'row override wins');
 assert.equal(resolveExecutionData(scope,planned[0].selection).testData.country,'US');
 assert.equal(executionPlan(scope,['TC_PROFILE'],{...request,tagExpression:'@smoke and (@admin or @support) and not @prod'}).length,1,'boolean tags select expected row');
 assert.throws(()=>executionPlan(scope,['TC_PROFILE'],{...request,tagExpression:'@smoke eval(1)'}),/Invalid/);
 const override={mode:'selected' as const,expectedVersion:state.version,credentialProfileIds:[profile.id,second.id]};
 assert.equal(executionPlan(scope,['TC_PROFILE'],override).length,2);
 assert.equal(fs.readFileSync(file,'utf8'),saved,'execution override never changes saved Examples');
 assert.equal(executionPlan(scope,['TC_PROFILE'],{...override,credentialProfileIds:[profile.id,second.id,third.id]}).length,3,'one case supports three selected users');
 assert.equal(executionPlan(scope,['TC_PROFILE'],{...request,mode:'selected',rows:rows.map((r,i)=>({...r,enabled:i!==0}))}).length,1,'disabled Examples do not execute');
 assert.equal(fs.readFileSync(file,'utf8'),saved,'execution override never changes saved Examples');
 assert.throws(()=>executionPlan(scope,['TC_PROFILE'],{...override,dataProfileIds:[data.id,data.id]}),/matrix/,'Cartesian expansion must be explicit');
 assert.equal(executionPlan(scope,['TC_PROFILE'],{...override,mode:'matrix',dataProfileIds:[data.id,data.id]}).length,4);
 process.env.AURA_EXECUTION_SELECTION=JSON.stringify(planned[0].selection);
 assert.equal(runtimeSelection()?.row.credentialProfileId,profile.id);
 const currentRegistry=JSON.parse(fs.readFileSync('ai/projects/registry.json','utf8'));currentRegistry.applications[0].environments.qa.credentials={email:'SYNTHETIC_LEGACY_EMAIL',password:'SYNTHETIC_LEGACY_PASSWORD'};writeFixtureFile('ai/projects/registry.json',JSON.stringify(currentRegistry));pinActiveScope({applicationId:scope.applicationId,environmentId:'qa'});
 process.env.SYNTHETIC_LEGACY_EMAIL='synthetic-legacy-user';process.env.SYNTHETIC_LEGACY_PASSWORD='synthetic-legacy-password';
 const runtimeCredentials=require('../../tests-e2e/support/env').credentials;
 assert.deepEqual(runtimeCredentials(),{email:'synthetic-operator',password:'synthetic-new-secret'},'explicit JSON profile takes precedence as a coherent unit');
 delete process.env.AURA_EXECUTION_SELECTION;assert.deepEqual(runtimeCredentials(),{email:'synthetic-legacy-user',password:'synthetic-legacy-password'},'legacy application credential bindings remain compatible');
 delete process.env.SYNTHETIC_LEGACY_EMAIL;delete process.env.SYNTHETIC_LEGACY_PASSWORD;
 process.env.AURA_EXECUTION_SELECTION=JSON.stringify({...planned[0].selection,applicationId:other.applicationId});assert.throws(runtimeSelection,/another application/);delete process.env.AURA_EXECUTION_SELECTION;
 assert.equal(diagnosticText('synthetic-operator synthetic-new-secret'), '[REDACTED] [REDACTED]');
 assert.ok(!JSON.stringify(diagnosticData({executionProfile:planned[0].profile,error:'synthetic-new-secret'})).includes('synthetic-new-secret'),'quarantine and screenshot metadata redact profile secrets');
 state=store.updateTestData(scope,state.version,{kind:'credential',profile:{id:profile.id,name:'Administrator',active:false}});
 assert.throws(()=>store.credentialPreflight(scope,profile.id),/CREDENTIAL_CONFIGURATION_FAILURE.*inactive/);
 assert.equal(classifyExecutionFailure('CREDENTIAL_CONFIGURATION_FAILURE: profile inactive'),'CREDENTIAL_CONFIGURATION_FAILURE');
 assert.equal(classifyExecutionFailure('Cloudflare 403 blocked'),'ENVIRONMENT_FAILURE');
 assert.equal(generatedInput('<data:customerName>'),'String(testData.customerName)');
 recording.actions[1].type='fill';recording.actions[1].value='<data:customerName>';
 const mapped=mapRecording(recording);assert.ok(mapped.fixtures.has('testData'));
 assert.ok(mapped.steps.flatMap(s=>s.code).join('\n').includes('String(testData.customerName)'),'generated code reads a data field rather than recording a profile value');
 assert.throws(()=>requiredData<Record<string,unknown>>({}).missing,/DATA_CONFIGURATION_FAILURE/,'missing data is a configuration failure');
 assert.equal(classifyExecutionFailure('DATA_CONFIGURATION_FAILURE: missing field'),'DATA_CONFIGURATION_FAILURE');
 const stable=fs.readFileSync(file,'utf8'),rename=fs.renameSync;fs.renameSync=()=>{throw Error('Synthetic atomic-write failure');};
 try{assert.throws(()=>store.updateTestData(scope,state.version,{kind:'credential',profile:{id:second.id,name:'Changed'}}),/Synthetic/);}finally{fs.renameSync=rename;}
 assert.equal(fs.readFileSync(file,'utf8'),stable,'failed atomic commit keeps prior JSON intact');
 const parsed=JSON.parse(stable);fs.writeFileSync(file,JSON.stringify({...parsed,schemaVersion:99}));assert.throws(()=>store.readTestData(scope),/schemaVersion/);fs.writeFileSync(file,stable);
 assert.throws(()=>store.dataFields({password:'forbidden'}),/Credential Profiles/);
 assert.throws(()=>store.dataFields(JSON.parse('{"__proto__":{"polluted":true}}')),/safe identifiers/);
 console.log('PASS Test Data: encrypted store, API boundary, profile lifecycle, Examples, execution planning, atomicity, isolation and redaction');
}
main().catch(error=>{console.error(error.message);process.exitCode=1;});
